### ISSUE TITLE
Error in latest VS

### ISSUE THREAD

**Issue by kant2002** [antofik/codeforces#7]
In the output window
```
Error 
System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at CodeforcesAddin.CodeforcesAddinPackage.ReadCurrentValues()
   at EnvDTE.Property.get_Value()
   at CodeforcesAddin.CodeforcesAddinPackage.ReadCurrentValues()
```

**Comment by antofik** [comment]
What is the version of VS?

**Comment by kant2002** [comment]
Vs 15.7 Community latest bits

**Comment by antofik** [comment]
Could you please share your *.csproj file? It looks like your project for some reason missing DefineConstants tag, or has incompatible version.

**Comment by kant2002** [comment]
It is Q# project. Initially I was not aware that extension is for C# only.
Your could think about Q# as extension to C#.
